#
# Makefile for Palm LifeDrive support
#

obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache.o
obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache-bl.o
obj-$(CONFIG_MACH_HTCAPACHE)        += htcapache-pm.o
