#
# Makefile for MIO A701
#

obj-$(CONFIG_MACH_MIOA701)		+= mioa701.o
obj-$(CONFIG_MACH_MIOA701_SOUND)	+= mioa701_sound.o
obj-$(CONFIG_MIOA701_BLUETOOTH) 	+= mioa701_bt.o
obj-$(CONFIG_MIOA701_GSM)	 	+= mioa701_phone.o
