#
# Makefile for MIO A701
#

obj-$(CONFIG_MACH_MIOA701)		+= mioa701.o mioa701_suspend.o
obj-$(CONFIG_MIOA701_BLUETOOTH) 	+= mioa701_bt.o
obj-$(CONFIG_MIOA701_GSM)	 	+= mioa701_phone.o
obj-$(CONFIG_MIOA701_GPS)	 	+= mioa701_gps.o
obj-$(CONFIG_MIOA701_PM)	 	+= mioa701_pm.o
obj-$(CONFIG_MIOA701_LEDS)	 	+= mioa701_leds.o
obj-$(CONFIG_MIOA701_UDC)		+= mioa701_udc.o
